import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:ilmai/models/user_model.dart';

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // Sign Up
  Future<String?> signUp(UserModel user, String password) async {
    try {
      UserCredential result = await _auth.createUserWithEmailAndPassword(
          email: user.email, password: password);
      
      // We use the UID generated by Firebase Auth
      final uid = result.user!.uid;

      // Create a map and ensure the UID is stored
      Map<String, dynamic> userData = user.toMap();
      userData['uid'] = uid; 
      userData['subscriptionTier'] = user.subscriptionTier;

      await _db.collection('users').doc(uid).set(userData);
      return null; 
    } catch (e) {
      return e.toString();
    }
  }

  // Sign In
  Future<String?> signIn(String email, String password) async {
    try {
      await _auth.signInWithEmailAndPassword(email: email, password: password);
      return null;
    } catch (e) {
      return e.toString();
    }
  }

  // Fetch Current User Data (For the Dashboard)
  Future<UserModel?> getUserData() async {
    try {
      User? currentUser = _auth.currentUser;
      if (currentUser != null) {
        DocumentSnapshot doc = await _db.collection('users').doc(currentUser.uid).get();
        if (doc.exists) {
          final data = doc.data() as Map<String, dynamic>;
          return UserModel(
            uid: data['uid'] ?? '',
            fullName: data['fullName'] ?? '',
            email: data['email'] ?? '',
            phone: data['phone'] ?? '',
            board: data['board'] ?? '',
          className: data['className'] ?? '',
          learningLevel: data['learningLevel'] ?? '',
          subscriptionTier: data['subscriptionTier'] ?? 'Pending',
        );
      }
      }
    } catch (e) {
      print("Error fetching user: $e");
    }
    return null;
  }

  // Sign Out
  Future<void> signOut() async {
    await _auth.signOut();
  }
}
