// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa7YLhvt7uXzwooTcHkCIKPob5PXC8qY4',
    appId: '1:321340615024:web:5cacad11f60187a80947b5',
    messagingSenderId: '321340615024',
    projectId: 'ilmai-34684',
    authDomain: 'ilmai-34684.firebaseapp.com',
    storageBucket: 'ilmai-34684.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnY0fIhv2qruoFarUxlRjs5L7FUwoAkPM',
    appId: '1:321340615024:android:1fdc826ca13d3f940947b5',
    messagingSenderId: '321340615024',
    projectId: 'ilmai-34684',
    storageBucket: 'ilmai-34684.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDepKII88RVdwQ1JMmrhWkdXLCpM-3Kbbc',
    appId: '1:321340615024:ios:de92d669614524660947b5',
    messagingSenderId: '321340615024',
    projectId: 'ilmai-34684',
    storageBucket: 'ilmai-34684.firebasestorage.app',
    iosBundleId: 'com.habban.ilmai.ilmai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDepKII88RVdwQ1JMmrhWkdXLCpM-3Kbbc',
    appId: '1:321340615024:ios:de92d669614524660947b5',
    messagingSenderId: '321340615024',
    projectId: 'ilmai-34684',
    storageBucket: 'ilmai-34684.firebasestorage.app',
    iosBundleId: 'com.habban.ilmai.ilmai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa7YLhvt7uXzwooTcHkCIKPob5PXC8qY4',
    appId: '1:321340615024:web:244814d9fa55c1a80947b5',
    messagingSenderId: '321340615024',
    projectId: 'ilmai-34684',
    authDomain: 'ilmai-34684.firebaseapp.com',
    storageBucket: 'ilmai-34684.firebasestorage.app',
  );
}
